### ISSUE TITLE
voltagedivider.rst

### ISSUE THREAD

**Issue by npadd1** [bobthechemist/feathercm#10]
Section 1.4: "Create a spreadsheet with columns for the number of turns, output voltage and calculated upper/lower voltages."
Should this say upper/lower resistors?

**Comment by bobthechemist** [comment]
(1) we only really need the lower voltage.  Is there a better way to phrase that?  What makes more sense when describing the two apparent resistors made in a potentiometer?

**Comment by npadd1** [comment]
RESISTORS

**Comment by bobthechemist** [comment]
Fixed with next push.
