### ISSUE TITLE
voltagedivider.rst

### ISSUE THREAD

**Issue by npadd1** [bobthechemist/feathercm#11]
"Voltage dividers cannot be used in bi-directional communication because it can only shift a voltage down. A 5 V source can be shifted down to 3.3 V, but a 3.3 V source cannot be shifted down to 5 V."

phrasing of this is unclear

**Comment by bobthechemist** [comment]
Attempted to rephrase with:

>Voltage dividers **cannot** be used in bi-directional communication because it can only shift a voltage *down*.  A 5 V source can be shifted down to 3.3 V, but it does not make sense to shift a 3.3 V source *down* to 5 V.

**Comment by npadd1** [comment]
That makes sense
